# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 611)
        MainWindow.setStyleSheet("QWidget {\n"
"   background-color: rgb(0, 0, 0);\n"
"    \n"
"\n"
"}\n"
"QMenuBar{\n"
"\n"
"  color: #90ee90\n"
"}\n"
" QMenu{\n"
"  color: #90ee90\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 551, 461))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(170, 255, 127);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.playlist = QtWidgets.QListWidget(self.centralwidget)
        self.playlist.setGeometry(QtCore.QRect(570, 40, 221, 421))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.playlist.setFont(font)
        self.playlist.setStyleSheet("color: rgb(0, 0, 214);\n"
"border-color: rgb(0, 0, 0);")
        self.playlist.setFrameShape(QtWidgets.QFrame.Panel)
        self.playlist.setResizeMode(QtWidgets.QListView.Adjust)
        self.playlist.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.playlist.setViewMode(QtWidgets.QListView.ListMode)
        self.playlist.setObjectName("playlist")
        self.prev = QtWidgets.QPushButton(self.centralwidget)
        self.prev.setGeometry(QtCore.QRect(170, 510, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.prev.setFont(font)
        self.prev.setStyleSheet("QPushButton{\n"
"\n"
"color: rgb(170, 255, 127);\n"
"\n"
"background-color: rgb(216, 230, 242);\n"
"border-top-left-radius:15px;\n"
"border-top-right-radius:15px;\n"
"border-bottom-left-radius:15px;\n"
"border-bottom-right-radius:15px;\n"
"\n"
"background-color: rgb(0, 0, 127);\n"
"\n"
"}\n"
"")
        self.prev.setText("")
        self.prev.setObjectName("prev")
        self.stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_btn.setGeometry(QtCore.QRect(110, 510, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.stop_btn.setFont(font)
        self.stop_btn.setStyleSheet("QPushButton{\n"
"\n"
"color: rgb(170, 255, 127);\n"
"\n"
"background-color: rgb(216, 230, 242);\n"
"border-top-left-radius:15px;\n"
"border-top-right-radius:15px;\n"
"border-bottom-left-radius:15px;\n"
"border-bottom-right-radius:15px;\n"
"background-color: rgb(0, 0, 127);\n"
"\n"
"}\n"
"")
        self.stop_btn.setText("")
        self.stop_btn.setObjectName("stop_btn")
        self.repeat = QtWidgets.QPushButton(self.centralwidget)
        self.repeat.setGeometry(QtCore.QRect(380, 520, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.repeat.setFont(font)
        self.repeat.setStyleSheet("QPushButton{\n"
"\n"
"color: rgb(170, 255, 127);\n"
"\n"
"background-color: rgb(216, 230, 242);\n"
"border-top-left-radius:15px;\n"
"border-top-right-radius:15px;\n"
"border-bottom-left-radius:15px;\n"
"border-bottom-right-radius:15px;\n"
"background-color: rgb(0, 0, 127);\n"
"\n"
"}\n"
"")
        self.repeat.setText("")
        self.repeat.setObjectName("repeat")
        self.volumeslider = QtWidgets.QSlider(self.centralwidget)
        self.volumeslider.setGeometry(QtCore.QRect(440, 530, 91, 16))
        self.volumeslider.setProperty("value", 20)
        self.volumeslider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeslider.setTickInterval(1)
        self.volumeslider.setObjectName("volumeslider")
        self.play_btn = QtWidgets.QPushButton(self.centralwidget)
        self.play_btn.setGeometry(QtCore.QRect(230, 510, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.play_btn.setFont(font)
        self.play_btn.setStyleSheet("QPushButton{\n"
"\n"
"color: rgb(170, 255, 127);\n"
"\n"
"\n"
"\n"
"border-top-left-radius:25px;\n"
"border-top-right-radius:25px;\n"
"border-bottom-left-radius:25px;\n"
"border-bottom-right-radius:25px;\n"
"\n"
"\n"
"background-color: rgb(0, 0, 127);\n"
"}\n"
"")
        self.play_btn.setText("")
        self.play_btn.setObjectName("play_btn")
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setGeometry(QtCore.QRect(310, 510, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.next.setFont(font)
        self.next.setStyleSheet("QPushButton{\n"
"\n"
"color: rgb(170, 255, 127);\n"
"background-color: rgb(0, 0, 127);\n"
"\n"
"border-top-left-radius:15px;\n"
"border-top-right-radius:15px;\n"
"border-bottom-left-radius:15px;\n"
"border-bottom-right-radius:15px;\n"
"\n"
"\n"
"}\n"
"")
        self.next.setText("")
        self.next.setObjectName("next")
        self.progressbar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressbar.setGeometry(QtCore.QRect(10, 470, 641, 31))
        self.progressbar.setStyleSheet("")
        self.progressbar.setProperty("value", 1)
        self.progressbar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressbar.setObjectName("progressbar")
        self.alllength = QtWidgets.QLabel(self.centralwidget)
        self.alllength.setGeometry(QtCore.QRect(730, 480, 55, 16))
        self.alllength.setStyleSheet("color: rgb(31, 168, 49);")
        self.alllength.setObjectName("alllength")
        self.songLengthLabel = QtWidgets.QLabel(self.centralwidget)
        self.songLengthLabel.setGeometry(QtCore.QRect(670, 480, 55, 16))
        self.songLengthLabel.setStyleSheet("color: rgb(31, 168, 49);")
        self.songLengthLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.songLengthLabel.setObjectName("songLengthLabel")
        self.lstlabel = QtWidgets.QLabel(self.centralwidget)
        self.lstlabel.setGeometry(QtCore.QRect(560, 0, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lstlabel.setFont(font)
        self.lstlabel.setStyleSheet("color: rgb(0, 78, 234);\n"
"\n"
"")
        self.lstlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lstlabel.setObjectName("lstlabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.openfile_action = QtWidgets.QAction(MainWindow)
        self.openfile_action.setObjectName("openfile_action")
        self.exit_action = QtWidgets.QAction(MainWindow)
        self.exit_action.setObjectName("exit_action")
        self.menufile.addAction(self.openfile_action)
        self.menufile.addSeparator()
        self.menufile.addAction(self.exit_action)
        self.menufile.addSeparator()
        self.menufile.addSeparator()
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Music Player"))
        self.alllength.setText(_translate("MainWindow", "00:00"))
        self.songLengthLabel.setText(_translate("MainWindow", "00:00"))
        self.lstlabel.setText(_translate("MainWindow", "List Play Waiting..."))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.openfile_action.setText(_translate("MainWindow", "Open file"))
        self.exit_action.setText(_translate("MainWindow", "exit"))
